version: '3.8'

services:
  teslashop:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: teslashop-docker
    container_name: teslashop
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/teslashop
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    # volumes:
    #   - ./:/var/www/teslashop

  db:
    image: mysql:latest
    container_name: tesla-shop
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
